### ISSUE TITLE
Remove .html from page URLs

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle.xyz#240]
Blog doesn't have a .html in the URL, whereas the rest of the pages (Community, Downloads, Privacy, Terms) do. Would be cool if we could remove the .html from all URLs.

**Comment by SNikhill** [comment]
@brandonhaslegs 

I am familiar with 2 ways. Modifying the `.htaccess` file (depends upon the server used) or making each page be served from the respective `index.html`.

Example for the 2nd option:
![image](https://user-images.githubusercontent.com/51415616/120495557-70f01080-c3da-11eb-8649-c4d7a99f5852.png)

In this case, the community page will be served from `index.html` located inside the `community` folder rather than `community.html`.

`blog` follows the 2nd method so, I am assuming you will like the same.

**Comment by brandonhaslegs** [comment]
@cloudhead Any thoughts here? Could we do this thing where we serve pages from inside a folder in order to get rid of `.html` in the URLs?
