### ISSUE TITLE
Following intro tutorial does seem to work

### ISSUE THREAD

**Issue by Gozala** [radicle-dev/radicle.xyz#59]
[Following tutorial](http://www.radicle.xyz/docs/#tutorial-1-contributor) after executing command:

```
rad project checkout 12D3KooWRsrUcqCFU3ompktgTo197gguibN3cjmgaoQy8AS54iHn
```

I end up with `radicle-garden` empty (git repo) directory

```sh
ls -a
.    ..   .git
```

While tutorial suggests there should be two more files:

> ```
> $ ls -a
> .  ..  .git  2019-03-01_tulip.txt  2019-03-02_mesa.txt
> ```

**Comment by jkarni** [comment]
This is an issue that should have been fixed earlier today. How did you install?

(The fix is to just do "git checkout master" inside the repo)

**Comment by jkarni** [comment]
We were previously doing a fetch (not pull) after being on master, but no checkout, so you'd get an empty master. We changed that recently and did upgrade the brew formula, but since it was pre-release thought we could get away with no version bump. It's a little mysterious to me that it seems like you got the older version. I'll look into it and report back.

**Comment by xla** [comment]
@Gozala Can you confirm that this is not an issue anymore with the latest binary you downloaded?

**Comment by Gozala** [comment]
Yes latest version fixed that
